corso_di_studio(3023, categoria_corso(l)).
corso_di_studio(3026, categoria_corso(l)).
corso_di_studio(5036, categoria_corso(lm)).
corso_di_studio(5045, categoria_corso(lm)).
corso_di_studio(5065, categoria_corso(lm)).
corso_di_studio(3068, categoria_corso(l)).
corso_di_studio(3011, categoria_corso(l)).
corso_di_studio(3057, categoria_corso(l)).
corso_di_studio(5048, categoria_corso(lm)).
corso_di_studio(5078, categoria_corso(lm)).
corso_di_studio(3051, categoria_corso(l)).
corso_di_studio(3072, categoria_corso(l)).
corso_di_studio(3071, categoria_corso(l)).
corso_di_studio(3004, categoria_corso(l)).
corso_di_studio(3062, categoria_corso(l)).
corso_di_studio(5053, categoria_corso(lm)).
corso_di_studio(3044, categoria_corso(l)).
corso_di_studio(3049, categoria_corso(l)).
corso_di_studio(5074, categoria_corso(lm6)).
corso_di_studio(5027, categoria_corso(lm6)).
corso_di_studio(3041, categoria_corso(l)).
corso_di_studio(3067, categoria_corso(l)).
corso_di_studio(3047, categoria_corso(l)).
corso_di_studio(5028, categoria_corso(lm)).
corso_di_studio(3042, categoria_corso(l)).
corso_di_studio(3040, categoria_corso(l)).
corso_di_studio(3048, categoria_corso(l)).
corso_di_studio(3014, categoria_corso(l)).
corso_di_studio(5049, categoria_corso(lm)).
corso_di_studio(5026, categoria_corso(lm6)).
corso_di_studio(3046, categoria_corso(l)).
corso_di_studio(3030, categoria_corso(l)).
corso_di_studio(5037, categoria_corso(lm)).
corso_di_studio(5077, categoria_corso(lm)).
corso_di_studio(5059, categoria_corso(lm)).
corso_di_studio(5076, categoria_corso(lm)).
corso_di_studio(3019, categoria_corso(l)).
corso_di_studio(5079, categoria_corso(lm5)).
corso_di_studio(3070, categoria_corso(l)).
corso_di_studio(5015, categoria_corso(lm)).
corso_di_studio(3061, categoria_corso(l)).
corso_di_studio(5008, categoria_corso(lm5)).
corso_di_studio(3027, categoria_corso(l)).
corso_di_studio(5009, categoria_corso(lm5)).
corso_di_studio(3000, categoria_corso(l)).
corso_di_studio(5068, categoria_corso(lm)).
corso_di_studio(3007, categoria_corso(l)).
corso_di_studio(5011, categoria_corso(lm)).
corso_di_studio(5005, categoria_corso(lm)).
corso_di_studio(5025, categoria_corso(lm)).
corso_di_studio(3054, categoria_corso(l)).
corso_di_studio(3006, categoria_corso(l)).
corso_di_studio(5050, categoria_corso(lm)).
corso_di_studio(3013, categoria_corso(l)).
corso_di_studio(5010, categoria_corso(lm)).
corso_di_studio(5003, categoria_corso(lm)).
corso_di_studio(3043, categoria_corso(l)).
corso_di_studio(5047, categoria_corso(lm)).
corso_di_studio(3017, categoria_corso(l)).
corso_di_studio(5063, categoria_corso(lm)).
corso_di_studio(3064, categoria_corso(l)).
corso_di_studio(3038, categoria_corso(l)).
corso_di_studio(5046, categoria_corso(lm)).
corso_di_studio(3066, categoria_corso(l)).
corso_di_studio(3063, categoria_corso(l)).
corso_di_studio(5080, categoria_corso(lm5)).
corso_di_studio(3052, categoria_corso(l)).
corso_di_studio(3021, categoria_corso(l)).
corso_di_studio(5029, categoria_corso(lm5)).
corso_di_studio(3010, categoria_corso(l)).
corso_di_studio(3029, categoria_corso(l)).
corso_di_studio(5072, categoria_corso(lm)).
corso_di_studio(5061, categoria_corso(lm)).
corso_di_studio(5018, categoria_corso(lm)).
corso_di_studio(5066, categoria_corso(lm)).
corso_di_studio(5039, categoria_corso(lm)).
corso_di_studio(3024, categoria_corso(l)).
corso_di_studio(3020, categoria_corso(l)).
corso_di_studio(5069, categoria_corso(lm)).
corso_di_studio(5075, categoria_corso(lm)).
corso_di_studio(5000, categoria_corso(lm)).
corso_di_studio(5014, categoria_corso(lm)).
corso_di_studio(5071, categoria_corso(lm)).
corso_di_studio(3022, categoria_corso(l)).
corso_di_studio(5043, categoria_corso(lm)).
corso_di_studio(3028, categoria_corso(l)).
corso_di_studio(5073, categoria_corso(lm)).
corso_di_studio(5062, categoria_corso(lm)).
corso_di_studio(995, categoria_corso(lm5)).
corso_di_studio(5064, categoria_corso(lm)).
corso_di_studio(3050, categoria_corso(l)).
corso_di_studio(5052, categoria_corso(lm)).
corso_di_studio(3069, categoria_corso(l)).
corso_di_studio(3065, categoria_corso(l)).
corso_di_studio(3060, categoria_corso(l)).
corso_di_studio(5054, categoria_corso(lm)).
corso_di_studio(5055, categoria_corso(lm)).
corso_di_studio(5013, categoria_corso(lm)).
corso_di_studio(5041, categoria_corso(lm)).
corso_di_studio(5081, categoria_corso(lm)).
corso_di_studio(3055, categoria_corso(l)).
corso_di_studio(3059, categoria_corso(l)).
corso_di_studio(5016, categoria_corso(lm)).
corso_di_studio(5044, categoria_corso(lm)).
corso_di_studio(3032, categoria_corso(l)).
corso_di_studio(5082, categoria_corso(lm)).
corso_di_studio(5051, categoria_corso(lm)).
corso_di_studio(5057, categoria_corso(lm)).
corso_di_studio(5070, categoria_corso(lm)).
