settore(ius).
settore(bio).
settore(med).
settore(ing_ind).
settore(mat).
settore(fis).
settore(icar).
settore(secs_p).
settore(m_psi).
settore(vet).
settore(geo).
settore(l_or).
settore(sps).
settore(chim).
settore(l_lin).
settore(m_ggr).
settore(l_fil_let).
settore(l_art).
settore(m_sto).
settore(m_fil).
settore(inf).
settore(agr).
settore(l_ant).
settore(m_edf).
settore(ing_inf).
settore(m_ped).
settore(secs_s).
settore(m_dea).
settore(null).
