di_riferimento(settore(ing_ind), corso(3057)).
di_riferimento(settore(med), corso(5027)).
di_riferimento(settore(secs_p), corso(3004)).
di_riferimento(settore(ing_ind), corso(3062)).
di_riferimento(settore(l_fil_let), corso(3051)).
di_riferimento(settore(bio), corso(5071)).
di_riferimento(settore(bio), corso(3047)).
di_riferimento(settore(m_ggr), corso(3060)).
di_riferimento(settore(fis), corso(5036)).
di_riferimento(settore(m_ped), corso(3038)).
di_riferimento(settore(icar), corso(3007)).
di_riferimento(settore(secs_s), corso(5003)).
di_riferimento(settore(chim), corso(3027)).
di_riferimento(settore(m_sto), corso(3069)).
di_riferimento(settore(chim), corso(5055)).
di_riferimento(settore(icar), corso(3059)).
di_riferimento(settore(m_ggr), corso(3014)).
di_riferimento(settore(ing_ind), corso(5014)).
di_riferimento(settore(secs_p), corso(5059)).
di_riferimento(settore(m_dea), corso(3017)).
di_riferimento(settore(l_ant), corso(5049)).
di_riferimento(settore(secs_p), corso(995)).
di_riferimento(settore(agr), corso(3057)).
di_riferimento(settore(ing_inf), corso(995)).
di_riferimento(settore(icar), corso(5037)).
di_riferimento(settore(bio), corso(5045)).
di_riferimento(settore(chim), corso(5064)).
di_riferimento(settore(inf), corso(3030)).
di_riferimento(settore(sps), corso(3032)).
di_riferimento(settore(bio), corso(5029)).
di_riferimento(settore(bio), corso(5027)).
di_riferimento(settore(vet), corso(3020)).
di_riferimento(settore(l_fil_let), corso(3038)).
di_riferimento(settore(bio), corso(3022)).
di_riferimento(settore(geo), corso(3007)).
di_riferimento(settore(mat), corso(3059)).
di_riferimento(settore(agr), corso(3049)).
di_riferimento(settore(ius), corso(3019)).
di_riferimento(settore(ing_ind), corso(5013)).
di_riferimento(settore(vet), corso(5045)).
di_riferimento(settore(l_lin), corso(3066)).
di_riferimento(settore(l_fil_let), corso(3017)).
di_riferimento(settore(secs_s), corso(5014)).
di_riferimento(settore(fis), corso(5079)).
di_riferimento(settore(ing_inf), corso(5013)).
di_riferimento(settore(ing_ind), corso(5011)).
di_riferimento(settore(sps), corso(3014)).
di_riferimento(settore(m_psi), corso(3067)).
di_riferimento(settore(mat), corso(5027)).
di_riferimento(settore(mat), corso(5037)).
di_riferimento(settore(mat), corso(3050)).
di_riferimento(settore(mat), corso(3024)).
di_riferimento(settore(icar), corso(3010)).
di_riferimento(settore(ing_inf), corso(5028)).
di_riferimento(settore(mat), corso(3010)).
di_riferimento(settore(fis), corso(3027)).
di_riferimento(settore(ing_inf), corso(3020)).
di_riferimento(settore(fis), corso(3040)).
di_riferimento(settore(fis), corso(3000)).
di_riferimento(settore(ius), corso(3060)).
di_riferimento(settore(bio), corso(5053)).
di_riferimento(settore(fis), corso(3024)).
di_riferimento(settore(l_lin), corso(3014)).
di_riferimento(settore(med), corso(3066)).
di_riferimento(settore(l_art), corso(5048)).
di_riferimento(settore(mat), corso(3030)).
di_riferimento(settore(ing_ind), corso(3061)).
di_riferimento(settore(m_psi), corso(5053)).
di_riferimento(settore(bio), corso(3044)).
di_riferimento(settore(ing_inf), corso(3007)).
di_riferimento(settore(m_sto), corso(5078)).
di_riferimento(settore(l_art), corso(3014)).
di_riferimento(settore(fis), corso(3019)).
di_riferimento(settore(fis), corso(3041)).
di_riferimento(settore(m_psi), corso(3047)).
di_riferimento(settore(bio), corso(5043)).
di_riferimento(settore(agr), corso(5077)).
di_riferimento(settore(bio), corso(5079)).
di_riferimento(settore(chim), corso(3028)).
di_riferimento(settore(ius), corso(5005)).
di_riferimento(settore(ius), corso(995)).
di_riferimento(settore(bio), corso(3064)).
di_riferimento(settore(ing_ind), corso(3054)).
di_riferimento(settore(sps), corso(5047)).
di_riferimento(settore(sps), corso(3013)).
di_riferimento(settore(m_dea), corso(5054)).
di_riferimento(settore(vet), corso(5064)).
di_riferimento(settore(m_psi), corso(5028)).
di_riferimento(settore(med), corso(3048)).
di_riferimento(settore(agr), corso(5065)).
di_riferimento(settore(chim), corso(5018)).
di_riferimento(settore(sps), corso(5066)).
di_riferimento(settore(ing_ind), corso(5000)).
di_riferimento(settore(bio), corso(3063)).
di_riferimento(settore(agr), corso(3068)).
di_riferimento(settore(agr), corso(3022)).
di_riferimento(settore(bio), corso(3049)).
di_riferimento(settore(secs_s), corso(3032)).
di_riferimento(settore(med), corso(5028)).
di_riferimento(settore(secs_s), corso(3004)).
di_riferimento(settore(geo), corso(3028)).
di_riferimento(settore(fis), corso(3042)).
di_riferimento(settore(m_fil), corso(3013)).
di_riferimento(settore(chim), corso(3011)).
di_riferimento(settore(secs_s), corso(5055)).
di_riferimento(settore(agr), corso(5043)).
di_riferimento(settore(m_fil), corso(5025)).
di_riferimento(settore(fis), corso(5029)).
di_riferimento(settore(m_psi), corso(5054)).
di_riferimento(settore(bio), corso(5072)).
di_riferimento(settore(ing_ind), corso(3010)).
di_riferimento(settore(ing_ind), corso(3019)).
di_riferimento(settore(secs_s), corso(3023)).
di_riferimento(settore(chim), corso(3024)).
di_riferimento(settore(med), corso(5045)).
di_riferimento(settore(secs_s), corso(5005)).
di_riferimento(settore(m_ped), corso(3067)).
di_riferimento(settore(secs_p), corso(5010)).
di_riferimento(settore(med), corso(3022)).
di_riferimento(settore(sps), corso(3051)).
di_riferimento(settore(icar), corso(5048)).
di_riferimento(settore(m_psi), corso(5027)).
di_riferimento(settore(chim), corso(5045)).
di_riferimento(settore(chim), corso(5000)).
di_riferimento(settore(med), corso(3019)).
di_riferimento(settore(mat), corso(3011)).
di_riferimento(settore(ius), corso(5048)).
di_riferimento(settore(mat), corso(3029)).
di_riferimento(settore(l_fil_let), corso(5046)).
di_riferimento(settore(ing_inf), corso(3004)).
di_riferimento(settore(ing_ind), corso(3007)).
di_riferimento(settore(secs_p), corso(3032)).
di_riferimento(settore(sps), corso(5077)).
di_riferimento(settore(secs_p), corso(3051)).
di_riferimento(settore(icar), corso(5043)).
di_riferimento(settore(fis), corso(3060)).
di_riferimento(settore(sps), corso(5010)).
di_riferimento(settore(fis), corso(3020)).
di_riferimento(settore(sps), corso(5078)).
di_riferimento(settore(ing_ind), corso(3050)).
di_riferimento(settore(med), corso(3047)).
di_riferimento(settore(med), corso(5071)).
di_riferimento(settore(med), corso(3043)).
di_riferimento(settore(secs_p), corso(5005)).
di_riferimento(settore(ing_ind), corso(3000)).
di_riferimento(settore(chim), corso(3023)).
di_riferimento(settore(med), corso(3044)).
di_riferimento(settore(mat), corso(3007)).
di_riferimento(settore(ius), corso(3046)).
di_riferimento(settore(icar), corso(5016)).
di_riferimento(settore(ius), corso(5047)).
di_riferimento(settore(fis), corso(3062)).
di_riferimento(settore(m_ggr), corso(5049)).
di_riferimento(settore(bio), corso(5026)).
di_riferimento(settore(bio), corso(3069)).
di_riferimento(settore(m_psi), corso(3046)).
di_riferimento(settore(chim), corso(5068)).
di_riferimento(settore(icar), corso(5018)).
di_riferimento(settore(chim), corso(3049)).
di_riferimento(settore(icar), corso(3057)).
di_riferimento(settore(ius), corso(5066)).
di_riferimento(settore(med), corso(5026)).
di_riferimento(settore(ius), corso(3010)).
di_riferimento(settore(vet), corso(5065)).
di_riferimento(settore(chim), corso(3007)).
di_riferimento(settore(m_edf), corso(5026)).
di_riferimento(settore(agr), corso(5064)).
di_riferimento(settore(l_fil_let), corso(3060)).
di_riferimento(settore(med), corso(3046)).
di_riferimento(settore(sps), corso(3066)).
di_riferimento(settore(m_psi), corso(3051)).
di_riferimento(settore(mat), corso(3027)).
di_riferimento(settore(bio), corso(3023)).
di_riferimento(settore(ing_inf), corso(5065)).
di_riferimento(settore(m_sto), corso(5048)).
di_riferimento(settore(m_dea), corso(5046)).
di_riferimento(settore(bio), corso(3062)).
di_riferimento(settore(bio), corso(5050)).
di_riferimento(settore(geo), corso(5061)).
di_riferimento(settore(inf), corso(5069)).
di_riferimento(settore(fis), corso(3043)).
di_riferimento(settore(mat), corso(5015)).
di_riferimento(settore(inf), corso(3027)).
di_riferimento(settore(bio), corso(5061)).
di_riferimento(settore(med), corso(5068)).
di_riferimento(settore(vet), corso(3022)).
di_riferimento(settore(l_fil_let), corso(5049)).
di_riferimento(settore(chim), corso(3068)).
di_riferimento(settore(m_sto), corso(5046)).
di_riferimento(settore(ius), corso(3038)).
di_riferimento(settore(secs_s), corso(5077)).
di_riferimento(settore(mat), corso(3022)).
di_riferimento(settore(m_ggr), corso(5078)).
di_riferimento(settore(med), corso(5079)).
di_riferimento(settore(med), corso(3023)).
di_riferimento(settore(med), corso(3042)).
di_riferimento(settore(sps), corso(3049)).
di_riferimento(settore(m_sto), corso(3060)).
di_riferimento(settore(med), corso(5055)).
di_riferimento(settore(bio), corso(3052)).
di_riferimento(settore(chim), corso(5065)).
di_riferimento(settore(bio), corso(5055)).
di_riferimento(settore(m_edf), corso(3019)).
di_riferimento(settore(chim), corso(3022)).
di_riferimento(settore(bio), corso(995)).
di_riferimento(settore(sps), corso(3006)).
di_riferimento(settore(secs_p), corso(5014)).
di_riferimento(settore(m_psi), corso(3041)).
di_riferimento(settore(icar), corso(3029)).
di_riferimento(settore(l_fil_let), corso(3013)).
di_riferimento(settore(sps), corso(3038)).
di_riferimento(settore(fis), corso(3023)).
di_riferimento(settore(l_art), corso(3057)).
di_riferimento(settore(l_art), corso(3051)).
di_riferimento(settore(m_ped), corso(3066)).
di_riferimento(settore(secs_s), corso(5047)).
di_riferimento(settore(fis), corso(5050)).
di_riferimento(settore(l_art), corso(5078)).
di_riferimento(settore(mat), corso(3020)).
di_riferimento(settore(bio), corso(3040)).
di_riferimento(settore(ing_ind), corso(5066)).
di_riferimento(settore(mat), corso(5069)).
di_riferimento(settore(med), corso(3049)).
di_riferimento(settore(bio), corso(3020)).
di_riferimento(settore(ing_inf), corso(3049)).
di_riferimento(settore(secs_p), corso(5003)).
di_riferimento(settore(m_psi), corso(3040)).
di_riferimento(settore(m_psi), corso(3042)).
di_riferimento(settore(ing_inf), corso(5016)).
di_riferimento(settore(ing_ind), corso(3011)).
di_riferimento(settore(m_psi), corso(5077)).
di_riferimento(settore(l_ant), corso(3014)).
di_riferimento(settore(l_lin), corso(3017)).
di_riferimento(settore(bio), corso(3028)).
di_riferimento(settore(m_sto), corso(3032)).
di_riferimento(settore(med), corso(5053)).
di_riferimento(settore(bio), corso(3041)).
di_riferimento(settore(ius), corso(5018)).
di_riferimento(settore(agr), corso(5000)).
di_riferimento(settore(l_fil_let), corso(3066)).
di_riferimento(settore(chim), corso(3026)).
di_riferimento(settore(vet), corso(5071)).
di_riferimento(settore(mat), corso(3000)).
di_riferimento(settore(agr), corso(3004)).
di_riferimento(settore(bio), corso(5080)).
di_riferimento(settore(mat), corso(5029)).
di_riferimento(settore(secs_p), corso(5077)).
di_riferimento(settore(l_fil_let), corso(5078)).
di_riferimento(settore(med), corso(3041)).
di_riferimento(settore(sps), corso(5044)).
di_riferimento(settore(med), corso(5000)).
di_riferimento(settore(m_dea), corso(3060)).
di_riferimento(settore(ing_ind), corso(5016)).
di_riferimento(settore(ius), corso(3041)).
di_riferimento(settore(fis), corso(3029)).
di_riferimento(settore(m_fil), corso(3038)).
di_riferimento(settore(bio), corso(3000)).
di_riferimento(settore(ius), corso(3052)).
di_riferimento(settore(chim), corso(3060)).
di_riferimento(settore(l_ant), corso(5025)).
di_riferimento(settore(l_ant), corso(3013)).
di_riferimento(settore(geo), corso(3029)).
di_riferimento(settore(bio), corso(5068)).
di_riferimento(settore(agr), corso(3020)).
di_riferimento(settore(chim), corso(5039)).
di_riferimento(settore(bio), corso(3042)).
di_riferimento(settore(fis), corso(3010)).
di_riferimento(settore(m_sto), corso(3017)).
di_riferimento(settore(l_art), corso(3060)).
di_riferimento(settore(bio), corso(5064)).
di_riferimento(settore(m_psi), corso(5074)).
di_riferimento(settore(fis), corso(3007)).
di_riferimento(settore(ius), corso(5050)).
di_riferimento(settore(agr), corso(5075)).
di_riferimento(settore(chim), corso(3000)).
di_riferimento(settore(ing_inf), corso(3010)).
di_riferimento(settore(fis), corso(5074)).
di_riferimento(settore(chim), corso(3020)).
di_riferimento(settore(l_fil_let), corso(3014)).
di_riferimento(settore(fis), corso(3061)).
di_riferimento(settore(ius), corso(3051)).
di_riferimento(settore(m_ggr), corso(5046)).
di_riferimento(settore(bio), corso(5074)).
di_riferimento(settore(ing_inf), corso(3014)).
di_riferimento(settore(secs_p), corso(5066)).
di_riferimento(settore(bio), corso(5000)).
di_riferimento(settore(ing_inf), corso(3050)).
di_riferimento(settore(fis), corso(3011)).
di_riferimento(settore(ius), corso(5003)).
di_riferimento(settore(ing_ind), corso(3049)).
di_riferimento(settore(agr), corso(3069)).
di_riferimento(settore(m_dea), corso(5025)).
di_riferimento(settore(agr), corso(3064)).
di_riferimento(settore(chim), corso(3064)).
di_riferimento(settore(agr), corso(3000)).
di_riferimento(settore(mat), corso(5079)).
di_riferimento(settore(ing_ind), corso(5075)).
di_riferimento(settore(l_lin), corso(5073)).
di_riferimento(settore(ing_inf), corso(5015)).
di_riferimento(settore(inf), corso(3010)).
di_riferimento(settore(vet), corso(3064)).
di_riferimento(settore(med), corso(5054)).
di_riferimento(settore(icar), corso(5011)).
di_riferimento(settore(fis), corso(5027)).
di_riferimento(settore(agr), corso(5045)).
di_riferimento(settore(med), corso(3040)).
di_riferimento(settore(chim), corso(3052)).
di_riferimento(settore(ius), corso(5045)).
di_riferimento(settore(sps), corso(3004)).
di_riferimento(settore(chim), corso(3029)).
di_riferimento(settore(fis), corso(3049)).
di_riferimento(settore(mat), corso(3069)).
di_riferimento(settore(secs_p), corso(5046)).
di_riferimento(settore(secs_p), corso(5026)).
di_riferimento(settore(fis), corso(5026)).
di_riferimento(settore(ius), corso(3006)).
di_riferimento(settore(bio), corso(5028)).
di_riferimento(settore(geo), corso(5043)).
di_riferimento(settore(ing_ind), corso(5074)).
di_riferimento(settore(m_psi), corso(3048)).
di_riferimento(settore(vet), corso(3068)).
di_riferimento(settore(chim), corso(5080)).
di_riferimento(settore(chim), corso(3010)).
di_riferimento(settore(ius), corso(5010)).
di_riferimento(settore(fis), corso(5069)).
di_riferimento(settore(med), corso(3006)).
di_riferimento(settore(mat), corso(5014)).
di_riferimento(settore(mat), corso(3062)).
di_riferimento(settore(m_ped), corso(5073)).
di_riferimento(settore(mat), corso(3061)).
di_riferimento(settore(fis), corso(3059)).
di_riferimento(settore(l_fil_let), corso(5048)).
di_riferimento(settore(fis), corso(3048)).
di_riferimento(settore(m_psi), corso(5050)).
di_riferimento(settore(ius), corso(5044)).
di_riferimento(settore(ing_inf), corso(5052)).
di_riferimento(settore(secs_p), corso(5044)).
di_riferimento(settore(sps), corso(5046)).
di_riferimento(settore(m_edf), corso(5028)).
di_riferimento(settore(m_psi), corso(3019)).
di_riferimento(settore(ius), corso(3028)).
di_riferimento(settore(chim), corso(5077)).
di_riferimento(settore(ing_inf), corso(5029)).
di_riferimento(settore(ius), corso(5028)).
di_riferimento(settore(agr), corso(5068)).
di_riferimento(settore(sps), corso(3067)).
di_riferimento(settore(bio), corso(5062)).
di_riferimento(settore(med), corso(5074)).
di_riferimento(settore(m_psi), corso(3044)).
di_riferimento(settore(med), corso(5050)).
di_riferimento(settore(fis), corso(3050)).
di_riferimento(settore(ing_inf), corso(5076)).
di_riferimento(settore(secs_s), corso(5059)).
di_riferimento(settore(chim), corso(5043)).
di_riferimento(settore(secs_p), corso(3038)).
di_riferimento(settore(vet), corso(3049)).
di_riferimento(settore(sps), corso(3042)).
di_riferimento(settore(chim), corso(5029)).
di_riferimento(settore(bio), corso(3048)).
di_riferimento(settore(l_or), corso(3017)).
di_riferimento(settore(secs_s), corso(3052)).
di_riferimento(settore(chim), corso(3062)).
di_riferimento(settore(m_psi), corso(5046)).
di_riferimento(settore(ing_inf), corso(3061)).
di_riferimento(settore(m_ggr), corso(3017)).
di_riferimento(settore(bio), corso(3024)).
di_riferimento(settore(m_sto), corso(3014)).
di_riferimento(settore(agr), corso(5029)).
di_riferimento(settore(geo), corso(5072)).
di_riferimento(settore(ing_ind), corso(3048)).
di_riferimento(settore(l_art), corso(3038)).
di_riferimento(settore(med), corso(3067)).
di_riferimento(settore(l_lin), corso(5049)).
di_riferimento(settore(bio), corso(3019)).
di_riferimento(settore(m_psi), corso(3043)).
di_riferimento(settore(chim), corso(3057)).
di_riferimento(settore(bio), corso(3067)).
di_riferimento(settore(m_ped), corso(5046)).
di_riferimento(settore(chim), corso(5041)).
di_riferimento(settore(bio), corso(3046)).
di_riferimento(settore(mat), corso(3054)).
di_riferimento(settore(fis), corso(3026)).
di_riferimento(settore(fis), corso(3030)).
di_riferimento(settore(m_psi), corso(3004)).
di_riferimento(settore(icar), corso(5066)).
di_riferimento(settore(secs_p), corso(3052)).
di_riferimento(settore(secs_p), corso(3006)).
di_riferimento(settore(icar), corso(3054)).
di_riferimento(settore(m_fil), corso(3051)).
di_riferimento(settore(agr), corso(3052)).
di_riferimento(settore(vet), corso(5029)).
di_riferimento(settore(m_dea), corso(5078)).
di_riferimento(settore(fis), corso(3044)).
di_riferimento(settore(vet), corso(5046)).
di_riferimento(settore(m_sto), corso(3051)).
di_riferimento(settore(icar), corso(3011)).
di_riferimento(settore(ing_ind), corso(3064)).
di_riferimento(settore(chim), corso(3069)).
di_riferimento(settore(med), corso(3063)).
di_riferimento(settore(bio), corso(3043)).
di_riferimento(settore(ius), corso(5078)).
di_riferimento(settore(chim), corso(3004)).
di_riferimento(settore(bio), corso(3013)).
di_riferimento(settore(ius), corso(5077)).
di_riferimento(settore(med), corso(5077)).
di_riferimento(settore(ing_ind), corso(5076)).
di_riferimento(settore(ius), corso(3013)).
di_riferimento(settore(agr), corso(3028)).
di_riferimento(settore(vet), corso(3000)).
di_riferimento(settore(ing_inf), corso(3011)).
di_riferimento(settore(m_psi), corso(5026)).
di_riferimento(settore(ius), corso(3032)).
di_riferimento(settore(secs_p), corso(5047)).
di_riferimento(settore(ius), corso(3004)).
di_riferimento(settore(chim), corso(5079)).
di_riferimento(settore(chim), corso(5062)).
di_riferimento(settore(mat), corso(3026)).
di_riferimento(settore(m_psi), corso(3038)).
di_riferimento(settore(fis), corso(5037)).
di_riferimento(settore(secs_p), corso(5050)).
di_riferimento(settore(fis), corso(3069)).
